### PR TITLE
Add SpinLock to guard NRT cache

### PR DESCRIPTION
**Pull request by weefuzzy**
An attempt to address #10 which I hope @tremblap  will be kind enough to road test for me

### CODE REVIEW

**Comment by tremblap** [comment]
It is the first PR on GitHub, I don't see how I can pull to test it... help!

**Comment by weefuzzy** [comment]
This could be clearer: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally

short version is that you can checkout a read-only version of the PR branch like 
```
git fetch origin pull/<pull request id>/head:<local branch name, whatever you want>
```
(assuming you've called your Github remote 'origin') So, in this case,e.g 

```
git fetch origin pull/11/head:sc-thread-crash
git checkout sc-thread-crash
```

**Comment by tremblap** [comment]
I'm trying to setup SourceTree to behave as well as it does with BitBucket and show them... not easy. if I run the first line you sent, I get it in the gui and then I can check it out there... maybe I could se pull as subtree in there.

**Comment by tremblap** [comment]
it works! - ok now to the thing at hand.

**Comment by tremblap** [comment]
It worked on Mac, now compiling Windows and Linux in parallel on two native machines...

**Comment by tremblap** [comment]
Linux - it works thrice in a row, more than 3 times faster than on Mac despite having half the cores and being 10 times older!

**Comment by tremblap** [comment]
on Windows, it works perfectly too. It does not solve the problem of 13-massive parallelisation on Linux, is that expected?

**Comment by weefuzzy** [comment]
It is. I think that problem is due to us making it possible to spawn an absurd number of threads all at once, which is a Bad Idea in general.

**Comment by tremblap** [comment]
so I should merge and accept pull request?

**Comment by weefuzzy** [comment]
Be my guest

**Pull request merged**
