### PR TITLE
created FluidFilesPath and a test file

### PR DESCRIPTION
**Pull request by tedmoore**
From Issue #40 

A class for easily accessing the Fluid example audio files.

See test file for use case example

### CODE REVIEW

**Comment by tremblap** [comment]
I think we'll need to test on all 3 platforms, right? It works well on MacOS for now.

To be in line with the rest we should add a .schelp file for it I think.

**Comment by tedmoore** [comment]
> To be in line with the rest we should add a .schelp file for it I think.

For sure. I'm still suggesting this as an interface and a tool. It's still open for debate.

**Comment by tremblap** [comment]
I love it.

**Review by tremblap — APPROVED** [review]
rock on - one help file and we're ready

**Pull request merged**
