### PR TITLE
Waveform spectrogram

### PR DESCRIPTION
**Pull request by tedmoore**
paired with https://github.com/flucoma/flucoma-core/pull/71

This implements the spectrogram feature for SuperCollider's `FluidWaveform`. There's a bit of refactoring that could still happen here, some in relation to the PR above, but for now I would like you to have a look at the arguments to `FluidWaveform` to see if they all make sense intuitively and they seem like the appropriate set of options. 

There is some code [here](https://github.com/flucoma/flucoma-docs/blob/sc-helpfiles-code/sc_code/Waveform.scd) for testing if you like (also I paste it below to avoid branch hopping).

```
s.boot;
// load a sound to slice
~drums = Buffer.read(s,FluidFilesPath("Nicol-LoopE-M.wav"));

// display
FluidWaveform(~drums,bounds:Rect(0,0,1200,300));

// show spectrogram
FluidWaveform(~drums,bounds:Rect(0,0,1200,300),showSpectrogram:true);

// spectrogram with some nice colors and a bit of styling...
FluidWaveform(~drums,bounds:Rect(0,0,1200,300),showSpectrogram:true,spectrogramColorScheme:1,waveformColor:Color.magenta(1,0.5),showWaveform:true);

// create a buffer to put indices into
~indices = Buffer(s);

// do a slice analysis
FluidBufAmpSlice.processBlocking(s,~drums,indices:~indices,fastRampUp: 10,fastRampDown: 2205,slowRampUp: 4410,slowRampDown: 4410,onThreshold: 10,offThreshold: 5,floor: -40,minSliceLength: 4410,highPassFreq: 20);

// plot the buffer with the indices overlayed
FluidWaveform(~drums,~indices,nil,Rect(0,0,800,200));

// do a descriptor analysis
~features = Buffer(s);
FluidBufLoudness.processBlocking(s,~drums,features:~features,action:{"done".postln;});

// copy just the first channel of that buffer to display it
~features2 = Buffer(s);
FluidBufCompose.processBlocking(s,~features,numChans:1,destination:~features2);

// plot the audio with the slices and the loudness analysis
FluidWaveform(~drums,~indices,~features2,Rect(0,0,1200,300));

// with gate info
~gate_analysis = Buffer(s);
FluidBufAmpGate.processBlocking(s,~drums,indices:~gate_analysis,onThreshold:-35,offThreshold:-35,minSliceLength:4410);

// it will plot the ons and offs
FluidWaveform(~drums,~gate_analysis,~features2,Rect(0,0,1200,300));

// do a descriptor analysis and plot both features either stacked or not:
~noisy = Buffer.read(s,FluidFilesPath("Tremblay-ASWINE-ScratchySynth-M.wav"));
~pitch_analysis = Buffer(s);

FluidBufPitch.processBlocking(s,~noisy,features:~pitch_analysis,action:{"done".postln;});

// plot not stacked:
FluidWaveform(~noisy,featureBuffer:~pitch_analysis,bounds:Rect(0,0,1200,300));

// plot stacked:
FluidWaveform(~noisy,featureBuffer:~pitch_analysis,bounds:Rect(0,0,1200,300),stackFeatures:true,waveformColor:Color(*0.9.dup(3)));

// add spectrogram:
FluidWaveform(~noisy,featureBuffer:~pitch_analysis,bounds:Rect(0,0,1200,300),stackFeatures:true,waveformColor:Color(0,0,0,0.5),showSpectrogram:true,spectrogramAlpha:0.5);
```

### CODE REVIEW

**Comment by jamesb93** [comment]
Just on a cursory glance I think that this is hugely divergent in interface from the Max version as most of the spectrogram and line drawing is handled by fav.js whereas yours is handrolled. Therefore I think this warrants a discussion between @tedmoore and @weefuzzy to see what the best path forward is.

**Comment by weefuzzy** [comment]
Nice @tedmoore, I dig very much. 

The coloured spectrogram is barfing at me (stack trace below), but everything else looks grand, and there's some ideas to steal for the Max version (the on/off regions, for instance).

I'm  not at all bothered about the differences in API, tbh, given the massive differences in how Max and SC deal with the whole issue of looking at things. 

If one wanted to use this in the context of a SC GUI (which is something I know literally nothing about), would that be desirable / possible? 

---

```
RECEIVER:
   nil
ARGS:
   Integer 140

PROTECTED CALL STACK:
	Meta_MethodError:new	0x7f81b84ffa00
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = nil
	Meta_DoesNotUnderstandError:new	0x7f81b85019c0
		arg this = DoesNotUnderstandError
		arg receiver = nil
		arg selector = at
		arg args = [ 140 ]
	Object:doesNotUnderstand	0x7f81e84a1280
		arg this = nil
		arg selector = at
		arg args = nil
	a FunctionDef	0x7f81b85d0980
		sourceCode = "<an open Function>"
		arg mag = 140
		arg index = 0
	ArrayedCollection:do	0x7f8188c2a8c0
		arg this = [ 140, 135, 108, 122, 133, 133, 129, 124, 113, 102, 115, 124, 128, 125, 113, 86, 104, 106, 101, 105, 104, 91, 87, 96, 95, 90, 80, 67, 58, 57, 48, 57, 70, 75, 71, 57, 70, 74, 70, 60, 59, 75, 80, 75, 66, 65, 63, 69, 72, 69, 56, 64, 71, 67, 52, 54, 67, 70, 68, 60, 58, 69, 71, 67, 59, 14, 60, 66, 62, 55, 46, 24, 55, 61, 63, 54, 41, 62, 61, 59, 65, 63, 50, 18, 57, 68, 71, 72, 71, 63, 23, 60, 68, 67, 63, 65, 67, 66, 64, 58, 55, 57, 59, 57, 47, 60, 65, 65, 66, 66, 67, 67, 58, 27, 56, 57, 35, 50, 65, 67, 62, 59, 53...etc...
		arg function = a Function
		var i = 0
	a FunctionDef	0x7f81b85d04c0
		sourceCode = "<an open Function>"
		var img = an Image
	Routine:prStart	0x7f81885afc00
		arg this = a Routine
		arg inval = 96362.575152404

CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	< closed FunctionDef >
		arg error = <instance of DoesNotUnderstandError>
	Integer:forBy
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_
		arg this = <instance of Scheduler>
		arg newSeconds = 96362.575194913
	Meta_AppClock:tick
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'at' not understood.
RECEIVER: nil
```

**Review by weefuzzy — CHANGES_REQUESTED** [review]
In favour. A help file would be good before merging...

**Comment by tedmoore** [comment]
> If one wanted to use this in the context of a SC GUI (which is something I know literally nothing about), would that be desirable / possible?

Not yet, but I'll do before merging. It's quite easy. FluidPlotter already operates this way.

**Comment by tedmoore** [comment]
@jamesb93 this seems to be failing the winbuild. Can you take a look?

**Comment by weefuzzy** [comment]
> @jamesb93 this seems to be failing the winbuild. Can you take a look?

Ninja installation failed on windows 😕 

>  Error retrieving packages from source 'https://community.chocolatey.org/api/v2/':
 Could not connect to the feed specified at 'https://community.chocolatey.org/api/v2/'. Please verify that the package source (located in the Package Manager Settings) is valid and ensure your network connectivity.
ninja not installed. The package was not found with the source(s) listed.
 Source(s): 'https://community.chocolatey.org/api/v2/'

Could be a one off burp, or maybe the ninja package has just changed on chocolatey...

**Comment by tedmoore** [comment]
ok, re running to see if it swallows its burp this time.

**Pull request merged**
