### PR TITLE
add Chroma feature

### PR DESCRIPTION
**Pull request by g-roma**

### CODE REVIEW

**Comment by tremblap** [comment]
OK I've pushed the helpfiles. Both toy examples crash, I'm recompiling in Test mode. 

@weefuzzy can you please proofread my explanations and parameter descriptions before I copy/paste in the Max ones.

@g-roma I'll post the results I get from the Test compile but the reproducible code is in both helpfiles. Very straightforward code.

**Comment by tremblap** [comment]
I found the crash: @g-roma can you push the object source please? I had the old compile of both with a different order and didn't compile since there are no 'source' for either.

**Comment by g-roma** [comment]
Sorry I had forgotten to commit the C++ code, is this related to the crash?

**Comment by tremblap** [comment]
yes it is - the version I had had less arguments so we were busting. I'm recompiling, stay tuned!

**Comment by tremblap** [comment]
Did you push? I cannot see an update with the C++

**Comment by g-roma** [comment]
it is the second commit in this PR

**Comment by tremblap** [comment]
ok I cannot see my helpfiles in the commit list of this PR, and fetch refuses to sync. Great. I'll try to pull from the terminal

**Comment by tremblap** [comment]
ok I broke the internet: by pushing on origin/pr/13 it created a branch named like that which has the helpfiles... and did not add to this PR. This is bad because now there is pr/13 in 2 places and it refuses to pull.

any idea how to sort this?

**Comment by tremblap** [comment]
I get this error:

fatal: Cannot fetch both refs/heads/pr/13 and refs/pull/13/head to refs/remotes/origin/pr/13

arghhhhhhh - I'll used the zipped version of the 2 c++ files to continue to work

**Comment by weefuzzy** [comment]
Yes. 

First, you need to change the mapping you made in ./git/config for fetches so that it doesn’t conflict with potential actual branch names in the ref tree. Here’s what I did 

fetch = +refs/pull/*/head:refs/gh-pull/remotes/origin/pr/*

Then you might need to unmap your local local pr/13 branch to stop it referring to this thing on the server

git branch --unset-upstream

Then try fetching and setting the upstream back to the correct thing. 

And don’t try and and push to pr branches, because they’re read-only :-D

**Comment by tremblap** [comment]
ok that didn't work. So I copied the files on the desktop. I should destroy the pr/13 I created on main but I'm afraid to kill the actual PR, can you do it @weefuzzy 

good news @g-roma nothing crashes and most things behave the way I thought they would. I propose we merge so I can push my helpfiles, once everything is unfucked.

**Comment by weefuzzy** [comment]
Rogue branch squished. Will merge now.

**Review by weefuzzy — APPROVED** [review]

**Pull request merged**
