### PR TITLE
Buf to kr enhancements

### PR DESCRIPTION
**Pull request by tedmoore**
From Issue #28 , added an optional argument to FluidBufToKr so that it can be initialized inside a SynthDef. This requires that a `numFrames` argument be supplied with the number of frames long that the buffer will be once supplied as an argument to a running synth.

Test code (with fixed version of `FluidBufToKr`):
```
(
// throws error because number of frames not specified
s.waitForBoot{
	Routine{
		~synth = {
			arg buf;
			FluidKrToBuf.kr(SinOsc.kr(Array.fill(5,{rrand(0.0,1.0)})),buf);

			FluidBufToKr.kr(buf).poll; ///////// this will now throw an error asking for a numFrames
		}.play;

		2.wait;

		~buffer = Buffer.alloc(s,5);
		s.sync;
		~synth.set(\buf,~buffer);
	}.play;
};
)

(
// works
s.waitForBoot{
	Routine{
		~synth = {
			arg buf;
			FluidKrToBuf.kr(SinOsc.kr(Array.fill(5,{rrand(0.0,1.0)})),buf);

			FluidBufToKr.kr(buf,5).poll; ////////// this will work becaues it knows how many frames the buffer will be
		}.play;

		2.wait;

		~buffer = Buffer.alloc(s,5);
		s.sync;
		~synth.set(\buf,~buffer);
	}.play;
};
)
```

### CODE REVIEW

**Comment by tedmoore** [comment]
For some reason the class file didn't commit. Probably user error. Please hold.

**Comment by jamesb93** [comment]
Just as a note, PR's need to have their base branch as `dev`. Seems that @weefuzzy got to it first, but just a heads up for the next ones :) Also are you force pushing @tedmoore to overwrite some mistakes or something? Nothing wrong with a `--force` every now and then but I'm curious if some part of the workflow is causing friction for you.

**Comment by tremblap** [comment]
interface question: is there no way to instead store the size at instantiation as an instance variable and not give the user the responsibility to give it manually? I wonder what would happen if:

1. I pass a buf of 10samps and specify 9 or 11 in that value
2. I pass a buf of the wrong size dynamically

I don't know how the error checking is and how sturdy it is and if the size has to be fixed at all (I suspect it has and therefore we need to check what is passed I think)

**Comment by tedmoore** [comment]
> some part of the workflow is causing friction for you.

Fork does a weird thing where sometimes it gets confused (or I get confused) saying that my origin and local are different even though I've just pushed (and I know that I was up to date). When this happens a quick force fixes it...

Anyone else have this weirdness happen? Next time it happens to me I'll take a screenshot and see if there are any suggestions.

**Comment by tedmoore** [comment]
These are good questions. I should probably lay out some more of my thinking:

> is there no way to instead store the size at instantiation as an instance variable 

Maybe I don't understand your suggestion, but I believe that's what this is doing. When one creates, instantiates, the SynthDef, they specify how many frames the buffer will be when then eventually set it as an argument to the Synth.

> and not give the user the responsibility to give it manually? 

There are a lot of times in SC when the user is responsible to give something manually, setting the numChannels in PlayBuf.ar for example (arguments like this are "not modulatable" as the help files like to say). This is basically the same thing, as the SynthDef won't know how many channels to allocate for the control stream output of FluidBufToKr unless the user specifies it.

> I wonder what would happen if:
> 1. I pass a buf of 10samps and specify 9 or 11 in that value
> 2. I pass a buf of the wrong size dynamically

This is all `BufWr.kr` and `BufRd.kr` under the hood (inside this pseudo-UGen). Both of those UGens will clip to the highest index if the index supplied is "out of bounds" of the buffer.

If you specify the number of frames to be 10 and pass a buffer with 9, you'll get back a 10 channel control stream, where the last two values are the same (both will read out of index 8 (zero counting)).

If you specify the number of frames to be 9 and pass a buffer with 10, you'll get out a 9 channel control stream that will read out the first 9 frames of the buffer.

If the user passes a buffer proper (as opposed to an OutputProxy (i.e. argument to the SynthDef)) the user can forgo, they want, specifying the number of frames because since it's a buffer, this can just check how many frames long it is.

> I don't know how the error checking is and how sturdy it is and if the size has to be fixed at all (I suspect it has and therefore we need to check what is passed I think)

There are error checks in here:
* a warning if the buffer has 0 frames
* a error if the buffer has > 1000 frames
* a very polite error if the buffer argument doesn't receive a buffer (because it is receiving an OutputProxy) _and_ numFrames isn't specified

The only other error I can think would be to use `BufChannels.kr` and `BufFrames.kr` to do error checking on the server as buffers are arriving dynamically. That to me seems more hand-holdy than SuperCollider usually is? Also, I don't know how to throw an error from the server!? Maybe that's a question for @weefuzzy.

There's a test file to try out too. https://github.com/flucoma/flucoma-sc/blob/BufToKr-enhancements/test/FluidBufToKr%20test.scd 

I'm happy to tweak the interface yet.

**Comment by tremblap** [comment]
> as the SynthDef won't know how many channels to allocate for the control stream output of FluidBufToKr unless the user specifies it.

As this is a pseudoUGen isn't there a way to call buf.numframes at instantiation and store that? Then the value will be stored and we remove one potential user error for free - it just sets it from the first buffer it is passed at instantiation. Or is your mod planning for people not to have to pass a buffer at all? If the latter, then I understand, but what we could do is to make a default of -1 which would then be captured if the user just provide a valid buffer and no 2nd argument?

**Review by tremblap — APPROVED** [review]
looks good to me

**Comment by tedmoore** [comment]
> Fork does a weird thing where sometimes it gets confused (or I get confused)

@jamesb93 I figured it out. It happens when I amend my commit. I see why as well. Ugh. But I like amending.

**Comment by weefuzzy** [comment]
> > Fork does a weird thing where sometimes it gets confused (or I get confused)
> 
> @jamesb93 I figured it out. It happens when I amend my commit. I see why as well. Ugh. But I like amending.

Just don't push until you're done with amendments then 😄

**Pull request merged**
